# Generated by Django 3.1.3 on 2022-02-03 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 2, 12, 21, 306633)),
        ),
        migrations.AddField(
            model_name='edu',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
