# Generated by Django 3.1.3 on 2022-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areum', '0002_auto_20220204_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='edu',
            name='category',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='edu',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
