# Generated by Django 3.1.3 on 2022-02-04 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areum', '0003_auto_20220204_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 30, 2, 509680)),
        ),
    ]
