# Generated by Django 3.1.3 on 2022-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areum', '0004_auto_20220204_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
